jinja2cpp/Jinja2Cpp

CMakeLists.txt
It worked locally with that same compiler. I'm using [this CI pipeline](https://gitlab.com/Manu343726/tinyrefl/pipelines/31812230) as reference.
=> Disable boost::recursive_wrapper maybe-uninitialized flags on GCC 6

include/jinja2cpp/reflected_value.h
I think that using a variant there is more correct, but this quick fix does the job
=> Do not require reflected types to be default constructible

README.md
Jinja2Cpp has five external dependencies: boost library (at least version 1.55) and several header-only dependecies from nonstd project(expected-lite, variant-lite, value-ptr-lite, optional-lite).
=> README.md - rm note about boost as only dep

src/filters.cpp, test/filters_test.cpp
The switch to stable_sort makes the `unique` operator deterministically return
the first unique elements.
Fixes Convert/FilterGenericTest/14:
jinja2cpp/test/test_tools.h:128
Expected: expectedResult
Which is: "['name', 'val']"
To be equal to: result
Which is: "['val', 'name']"
and Unique/ListIteratorTest/9:
jinja2cpp/test/filters_test.cpp:28
Expected: expectedResult
Which is: "test string 0, test string 1"
To be equal to: result
Which is: "test string 0, test string 5"
=> Fix filters_tests that depend on sorting order

src/internal_value.h
This fixes the build with libcxx which currently fails with:
```
In file included from jinja2cpp/src/filters.cpp:1:
In file included from jinja2cpp/src/filters.h:4:
In file included from jinja2cpp/src/expression_evaluator.h:4:
In file included from jinja2cpp/src/internal_value.h:4:
In file included from jinja2cpp/include/jinja2cpp/value.h:6:
In file included from libcxx/include/vector:274:
In file included from libcxx/include/__bit_reference:15:
libcxx/include/algorithm:2493:5: error: static_assert failed due to requirement '__is_forward_iterator<Iterator>::value' "std::max_element requires a ForwardIterator"
static_assert(__is_forward_iterator<_ForwardIterator>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Tag ListAdapter::Iterator as a forward iterator

.gitignore, src/filters.cpp, src/filters.h, test/filters_test.cpp, test/test_tools.h, test/user_callable_test.cpp
Attribute "default" was required by filter "map", but as "map" uses filter "attr" for each collection entity, "default" supported for "attr" too.
=> Supported attribute "default" for filters "attr" and "map" to resolve #48.

src/helpers.h, src/lexertk.h, src/template_parser.h, test/basic_tests.cpp, test/helpers_tests.cpp
Supported next characters: \n, \r and \t.
=> Supports for escape characters in the string literals. Resolves #49.

src/helpers.h, src/template_parser.h
As per our discussion at
https://github.com/jinja2cpp/Jinja2Cpp/pull/124
I am providing a fix that uses StringConverter::DoConvert.
The return value of wcsrtombs/mbsrtowcs is compared against (size_t)-1, because this is how the functions' documentation states it.
=> Fix a buffer overrun in ParserTraits::GetAsString (second pull request)

README.md, src/string_converter_filter.cpp, test/filters_test.cpp
Fixes #137 
Note that [the documentation](https://jinja.palletsprojects.com/en/2.10.x/templates/#capitalize) says
```
The first character will be uppercase, all others lowercase.
```
Here we look for the first (alphanumeric) character, pass it to `std::toupper`, then pass the remaining alphanumeric characters through `std::tolower`. Let me know if the desired behavior of the filter is different from this and I'll modify the PR accordingly.
=> add CapitalMode to StringConverter::Filter

include/jinja2cpp/error_info.h, src/error_info.cpp, src/lexer.h, src/template_parser.h, test/errors_test.cpp, test/statements_tets.cpp
Solves https://github.com/jinja2cpp/Jinja2Cpp/issues/146
=> Implement raw/endraw 

src/filters.cpp, src/filters.h, test/filters_test.cpp
Batch filter implementation: #136 .
=> Batch filter (solves #136)

src/value_visitors.h, test/expressions_test.cpp
Solves https://github.com/jinja2cpp/Jinja2Cpp/issues/158
=> Repeat string

src/filters.cpp, test/filters_test.cpp
I have seen someone else implemented some batch version, which looks quite different from the described task though and has no tests yet. Therefore i made sure the batch version is working just as before. Any suggestions on what to do with the batch version?
The slice is for now only implmented for lists and will return some default empty in case of other types. There are some tests for the basic functionality.
I am open for further wishes / adjustments :)
=> filter slice: implement non-batch version with tests (#141)

.github/workflows/linux-build.yml, README.md, src/filters.cpp, src/filters.h, src/string_converter_filter.cpp, test/filters_test.cpp
* Added implementation for `striptags` filter + tests (#175)
* Entry added to the list of supported filters in README.
=> Added `striptags` filter

README.md, src/filters.cpp, src/filters.h, src/string_converter_filter.cpp, test/filters_test.cpp
Implemention of the center filter https://github.com/jinja2cpp/Jinja2Cpp/issues/171
=> Add center filter

include/jinja2cpp/template_env.h
The compiler will give an error on the file `include/jinja2cpp/template_env.h` concerning the `std::unique_lock` is not included from the standard c++ template library until the patch is included.
The patch is briefly short:
```c++
diff --git a/include/jinja2cpp/template_env.h b/include/jinja2cpp/template_env.h
index d49859e..0bd456e 100644
--- a/include/jinja2cpp/template_env.h
+++ b/include/jinja2cpp/template_env.h
@@ -6,6 +6,7 @@
#include "filesystem_handler.h"
#include "template.h"
+#include <mutex>
#include <shared_mutex>
#include <unordered_map>
```
It adresses and patches the compiler error shown below:
```cmake
[  4%] Building CXX object CMakeFiles/jinja2cpp.dir/src/error_info.cpp.o
[  6%] Building CXX object CMakeFiles/jinja2cpp.dir/src/expression_evaluator.cpp.o
[  9%] Building …
```
=> ADD include of a c++ stl file in main library to patch compiler error

src/filters.cpp
https://github.com/jinja2cpp/Jinja2Cpp/issues/208
Here is how I think this can be fixed.
=> Issue 208 - No error when filter is unknown

CMakeLists.txt
Use content of BUILD_SHARED_LIBS to initialize JINJA2CPP_BUILD_SHARED_LIBS
=> Fix library always being generated as shared library

src/testers.cpp, test/testers_test.cpp
In the original Jinja, when the 'in' operator is applied to strings it searches for a substring.
It happens naturally, as a string is a list of chars in Python. This logic wasn't translated to Jinja2cpp right away.
Examples:
AS IS:
```
'b' in 'abc' -> false
'abc' in 'b' -> false
```
EXPECTED:
```
'b' in 'abc' -> true
'abc' in 'b' -> false
```
This PR proposes a fix: expect two possible types of inputs - strings and lists. 
Lists are being treated the same way as before, for strings `sequence::find(substring)` is applied.
=> Mimic the behavior of the 'in' operator when applied to strings

cmake/public/jinja2cpp-config.cmake.in
=> Fix CMake find_package

src/expression_parser.cpp, test/expressions_test.cpp
Jinja2Cpp parses {] as an empty dictionary and fails to parse {}.
I expected the opposite behaviour.
=> Fix empty dict literal parsing

src/filters.cpp
`reverse` was providing stale string_views (pointing to garbage). 
The cause was that the data was not being protected, I'm copying the fix from what DictSort was doing.
(also applying the protection to the other filters)
=> Fixing missing life rage protection for the reverse filter (and others).

thirdparty/internal_deps.cmake
Otherwise, currently `find_package` can find `RapidJSON` installed on the system to default paths.
=> Cmake finds only downloaded rapidjson

thirdparty/external_boost_deps.cmake
In order to use Jinja2CPP with vcpkg it requires boost::lexical-cast library.
After this change it will be possible to use Jinja2CPP as vcpkg library as requested here #194
=> Update boost dependencies

thirdparty/internal_deps.cmake
We don't need to prepend Android build root, since we are finding RapidJson by absolute path
=> Fixed cross-compilation for Android

src/serialize_filters.cpp
accumulate cpy full string on each char, I replaced it with std::string::push_back/append, now its complexity is amortized linear
=> Fix quadric memcpy on toJson

include/jinja2cpp/polymorphic_value.h, thirdparty/internal_deps.cmake
Specifically, it's must have to pick up this patch https://github.com/martinmoene/string-view-lite/commit/5f32805d5b8c4bd478b5f3ca39b8b0789d4a0bcc to fix compilation on MSVC 2024 14.41
Verified by https://github.com/openvinotoolkit/openvino.genai/pull/942
=> Updated some dependencies versions to latest state
